name: Setting Template
description: 개발관련 셋팅을 설정할 때 쓰는 템플릿
title: "[Setting] Setting Title"
labels: ["⚒️SETTING"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: Setting 설명
      description: 작업할 setting에 대한 설명을 적어주세요.
      placeholder: ex. 개발시 필요한 spm을 설치합니다.
    validations:
      required: true
      
